
package main;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.proteanit.sql.DbUtils;

public class frmExpense extends javax.swing.JFrame {
ResultSet rs;
Connection conn;
PreparedStatement pstmt;
boolean add,edit;
String getSelectedID;
    public frmExpense() {
        initComponents();
        doConnect();
        clearTexts();
        lockTexts();
        fillTable();
        setLocationRelativeTo(null);
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {listenSearch();}
            @Override
            public void removeUpdate(DocumentEvent e) {listenSearch();}
            @Override
            public void changedUpdate(DocumentEvent e) {listenSearch();}
        });
    }
private void listenSearch(){
    try{
        String searchSQL = "Select * from tblcustomer where customer_name like? OR customer_address like? OR customer_contact like?";
        pstmt = conn.prepareStatement(searchSQL);
        pstmt.setString(1,"%"+txtSearch.getText()+"%");
        pstmt.setString(2,"%"+txtSearch.getText()+"%");
        pstmt.setString(3,"%"+txtSearch.getText()+"%");
        rs = pstmt.executeQuery();
        tblcustomer.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(SQLException e){
        e.getMessage();
    }
}
private void sortTable(){
    tblcustomer.getColumnModel().getColumn(0).setHeaderValue("ID");
    tblcustomer.getColumnModel().getColumn(1).setHeaderValue("Name");
    tblcustomer.getColumnModel().getColumn(2).setHeaderValue("Address");
    tblcustomer.getColumnModel().getColumn(3).setHeaderValue("Contact Details");
    
    tblcustomer.getColumnModel().getColumn(0).setPreferredWidth(25);
    tblcustomer.getColumnModel().getColumn(1).setPreferredWidth(100);
    tblcustomer.getColumnModel().getColumn(2).setPreferredWidth(250);
    tblcustomer.getColumnModel().getColumn(3).setPreferredWidth(100);
    tblcustomer.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
}
private void fillTable(){
    try{
        String fillTable = "Select * from tblcustomer";
        pstmt = conn.prepareStatement(fillTable);
        rs = pstmt.executeQuery();
        tblcustomer.setModel(DbUtils.resultSetToTableModel(rs));
        tblcustomer.setAutoCreateRowSorter(true);
        sortTable();
    }catch(SQLException e){
        e.getMessage();
    }
}    
 
private void unlockTexts(){
    txtContact.setEnabled(true);
    txtCustomerAddress.setEnabled(true);
    txtCustomerName.setEnabled(true);
   
}    
private void lockTexts(){
    txtContact.setEnabled(false);
    txtCustomerAddress.setEnabled(false);
    txtCustomerName.setEnabled(false);
   
}    
private void clearTexts(){
    txtContact.setText("");
    txtCustomerName.setText("");
    txtCustomerAddress.setText("");
}    
private void doConnect(){
try{
    Class.forName("com.mysql.jdbc.Driver");
    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbebpos","root","rootroot");
}catch(SQLException | ClassNotFoundException e){
    JOptionPane.showMessageDialog(this, e.getMessage());
}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblcustomer = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblcustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcustomer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 600, 520));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 330, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 50));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 490, 60));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 50));
        jPanel2.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 330, 50));

        txtCustomerName.setNextFocusableComponent(txtCustomerAddress);
        jPanel2.add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 330, 50));
        jPanel2.add(txtCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 330, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact Details:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer Name:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 50));

        btnAdd.setText("ADD");
        btnAdd.setFocusCycleRoot(true);
        btnAdd.setNextFocusableComponent(txtCustomerName);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 60, 50));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 60, 50));

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 70, 20));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 60, 50));

        btnCancel.setText("CANCEL");
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 70, 20));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 500, 430));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 590));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("NEW");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("SAVE");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        add = true;
        edit = false;
        unlockTexts();
        clearTexts();
        txtCustomerName.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        edit = true;
        add =false;
        unlockTexts();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        if (add == true && edit ==false){
            try{
                String insertSQLQuery = "INSERT INTO tblcustomer (customer_name,customer_address,customer_contact) "
                        + "values (?,?,?)";
                pstmt = conn.prepareStatement(insertSQLQuery);
                pstmt.setString(1,txtCustomerName.getText());
                pstmt.setString(2,txtCustomerAddress.getText());
                pstmt.setString(3, txtContact.getText());
                pstmt.execute();
                JOptionPane.showMessageDialog(this, "Customer Added");
                pstmt.close();
                fillTable();
                clearTexts();
                lockTexts();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }else if (add == false && edit == true){
            try{
                String updateTblCustomer = "UPDATE tblcustomer set customer_name=?,customer_address=?,customer_contact=? where customer_id=?";
                pstmt = conn.prepareStatement(updateTblCustomer);
                pstmt.setString(1,txtCustomerName.getText());
                pstmt.setString(2,txtCustomerAddress.getText());
                pstmt.setString(3, txtContact.getText());           
                pstmt.setString(4, getSelectedID);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Customer details updated");
                pstmt.close();
                fillTable();
                clearTexts();
                lockTexts();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcustomerMouseClicked
        int row = tblcustomer.getSelectedRow();
        int ba = tblcustomer.convertRowIndexToModel(row);
        try{
            String tblClick = (tblcustomer.getModel().getValueAt(ba, 0).toString());
            String tableQuery = "Select * from tblcustomer where customer_id=?";
            pstmt = conn.prepareStatement(tableQuery);
            pstmt.setString(1, tblClick);
            rs = pstmt.executeQuery();
            if (rs.next()){
                txtCustomerAddress.setText(rs.getString("customer_address"));
                txtCustomerName.setText(rs.getString("customer_name"));
                txtContact.setText(rs.getString("customer_contact"));
                getSelectedID= rs.getString("customer_id");
            }
        }catch(SQLException e){
            e.getMessage();
        }
    }//GEN-LAST:event_tblcustomerMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        btnAddActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        btnSaveActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        frmModulePicker obj = new frmModulePicker();
        obj.setVisible(true);
        this.dispose();
        try{
        pstmt.close();
        conn.close();
        rs.close();
        }catch(SQLException e){e.getMessage();}
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int itemSelected = JOptionPane.showConfirmDialog(this, "DELETE RECORD?","DELETE",JOptionPane.YES_NO_OPTION);
        if (itemSelected==JOptionPane.YES_OPTION){
            try{
                pstmt = conn.prepareStatement("DELETE FROM tblProduct where productId=?");
                pstmt.setString(1,txtCustomerName.getText());
                pstmt.executeUpdate();
                pstmt.close();
                JOptionPane.showMessageDialog(this, "RECORD DELETED");
                clearTexts();
                fillTable();
            }catch(SQLException e){
                e.getMessage();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmExpense().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcustomer;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
