
package main;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.proteanit.sql.DbUtils;

public class frmProduct extends javax.swing.JFrame {
ResultSet rs;
Connection conn;
PreparedStatement pstmt;
boolean add,edit;
String getProductID;
    public frmProduct() {
        initComponents();
        doConnect();
        clearTexts();
        lockTexts();
        fillTable();
        setLocationRelativeTo(null);
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {listenSearch();}
            @Override
            public void removeUpdate(DocumentEvent e) {listenSearch();}
            @Override
            public void changedUpdate(DocumentEvent e) {listenSearch();}
        });
    }
private void listenSearch(){
    try{
        String searchSQL = "Select * from tblwrs_product where product_name like? OR product_id like?";
        pstmt = conn.prepareStatement(searchSQL);
        pstmt.setString(1,"%"+txtSearch.getText()+"%");
        pstmt.setString(2,"%"+txtSearch.getText()+"%");
        rs = pstmt.executeQuery();
        tableProduct.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(SQLException e){
        e.getMessage();
    }
}
private void sortTable(){
    tableProduct.getColumnModel().getColumn(0).setHeaderValue("ID");
    tableProduct.getColumnModel().getColumn(1).setHeaderValue("NAME");
    tableProduct.getColumnModel().getColumn(2).setHeaderValue("PRICE");
    tableProduct.getColumnModel().getColumn(3).setHeaderValue("QOH");
    tableProduct.getColumnModel().getColumn(4).setHeaderValue("MIN");
    tableProduct.getColumnModel().getColumn(5).setHeaderValue("MAX");
    
    tableProduct.getColumnModel().getColumn(0).setPreferredWidth(50);
    tableProduct.getColumnModel().getColumn(1).setPreferredWidth(150);
    tableProduct.getColumnModel().getColumn(2).setPreferredWidth(50);
    tableProduct.getColumnModel().getColumn(3).setPreferredWidth(50);
    tableProduct.getColumnModel().getColumn(4).setPreferredWidth(50);
    tableProduct.getColumnModel().getColumn(5).setPreferredWidth(50);
    tableProduct.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
}
private void fillTable(){
    try{
        String fillTable = "Select * from tblwrs_product";
        pstmt = conn.prepareStatement(fillTable);
        rs = pstmt.executeQuery();
        tableProduct.setModel(DbUtils.resultSetToTableModel(rs));
        tableProduct.setAutoCreateRowSorter(true);
        sortTable();
    }catch(SQLException e){
        e.getMessage();
    }
}    

private void unlockTexts(){
    txtPrice.setEnabled(true);
    txtProductName.setEnabled(true);
    txtStock.setEnabled(true);
    txtMax.setEnabled(true);
    txtMin.setEnabled(true);
}    
private void lockTexts(){
    txtPrice.setEnabled(false);
    txtProductName.setEnabled(false);
    txtStock.setEnabled(false);
    txtMax.setEnabled(false);
    txtMin.setEnabled(false);
}    
private void clearTexts(){
    txtPrice.setText("");
    txtStock.setText("");
    txtProductName.setText("");
    txtMax.setText("");
    txtMin.setText("");
}    
private void doConnect(){
try{
    Class.forName("com.mysql.jdbc.Driver");
    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbebpos","root","rootroot");
}catch(SQLException | ClassNotFoundException e){
    JOptionPane.showMessageDialog(this, e.getMessage());
}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduct = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtPrice = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProduct);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 600, 520));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 230, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 50));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 390, 60));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrice.setNextFocusableComponent(txtStock);
        jPanel2.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 230, 50));

        jPanel2.add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 230, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Min:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 50, 70));

        txtStock.setNextFocusableComponent(txtMin);
        jPanel2.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 50, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Initial Stock:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 50));

        txtMin.setNextFocusableComponent(txtMax);
        jPanel2.add(txtMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 110, 70));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Max:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 50, 70));

        txtMax.setNextFocusableComponent(btnSave);
        jPanel2.add(txtMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 110, 70));

        btnAdd.setText("ADD");
        btnAdd.setFocusCycleRoot(true);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 70, 50));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel2.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 70, 50));

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 70, 50));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 70, 40));

        btnCancel.setText("CANCEL");
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 70, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Product Name:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 50));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 480, 430));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 590));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("NEW");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("SAVE");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        add = true;
        edit = false;
        unlockTexts();
        clearTexts();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        edit = true;
        add =false;
        unlockTexts();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        if (add == true && edit ==false){
            try{
                String insertQuery = "INSERT INTO tblwrs_product (product_name,product_price,product_qoh,product_min,product_max) "
                        + "values (?,?,?,?,?)";
                pstmt = conn.prepareStatement(insertQuery);
                pstmt.setString(1,txtProductName.getText());
                pstmt.setString(2, txtPrice.getText());
                pstmt.setInt(3,Integer.valueOf(txtStock.getText()));
                pstmt.setInt(4, Integer.valueOf(txtMin.getText()));
                pstmt.setInt(5, Integer.valueOf(txtMax.getText()));
                pstmt.execute();
                JOptionPane.showMessageDialog(this, "Product Added");
                pstmt.close();
                fillTable();
                clearTexts();
                lockTexts();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }else if (add == false && edit == true){
            try{
                String updateSQL = "UPDATE tblwrs_product set product_name=?,product_price=?,product_qoh=?,product_min=?,product_max=?"
                        + " where product_id=?";
                pstmt = conn.prepareStatement(updateSQL);
                pstmt.setString(1,txtProductName.getText());
                pstmt.setString(2, txtPrice.getText());
                pstmt.setInt(3,Integer.valueOf(txtStock.getText()));
                pstmt.setInt(4, Integer.valueOf(txtMin.getText()));
                pstmt.setInt(5, Integer.valueOf(txtMax.getText()));                
                pstmt.setString(6, getProductID);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Product Updated");
                pstmt.close();
                fillTable();
                clearTexts();
                lockTexts();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tableProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductMouseClicked
        int row = tableProduct.getSelectedRow();
        int ba = tableProduct.convertRowIndexToModel(row);
        try{
            String tblClick = (tableProduct.getModel().getValueAt(ba, 0).toString());
            String tableQuery = "Select * from tblwrs_product where product_id=?";
            pstmt = conn.prepareStatement(tableQuery);
            pstmt.setString(1, tblClick);
            rs = pstmt.executeQuery();
            if (rs.next()){
                txtProductName.setText(rs.getString("product_name"));
                txtPrice.setText(rs.getString("product_price"));
                txtStock.setText(String.valueOf(rs.getInt("product_qoh")));
                txtMin.setText(String.valueOf(rs.getInt("product_min")));
                txtMax.setText(String.valueOf(rs.getInt("product_max")));
                getProductID= rs.getString("product_id");
            }
        }catch(SQLException e){
            e.getMessage();
        }
    }//GEN-LAST:event_tableProductMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        btnAddActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        btnSaveActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        frmModulePicker obj = new frmModulePicker();
        obj.setVisible(true);
        this.dispose();
        try{
        pstmt.close();
        conn.close();
        rs.close();
        }catch(SQLException e){e.getMessage();}
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int itemSelected = JOptionPane.showConfirmDialog(this, "DELETE RECORD?","DELETE",JOptionPane.YES_NO_OPTION);
        if (itemSelected==JOptionPane.YES_OPTION){
            try{
                pstmt = conn.prepareStatement("DELETE FROM tblwrs_product where product_id=?");
                pstmt.executeUpdate();
                pstmt.close();
                JOptionPane.showMessageDialog(this, "RECORD DELETED");
                clearTexts();
                fillTable();
            }catch(SQLException e){
                e.getMessage();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProduct;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
